project_id = "nbuilebrjptbbogcfqdh"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.delete-user]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.list-user-emails]
    verify_jwt = false
  [functions.wappfly-webhook]
    verify_jwt = false
  [functions.get-wappfly-webhook-url]
    verify_jwt = false
